Repository GerardinClement/gbmu, pull requests merged in 2025-07, with the labels that each got.

#19 [FIX] fix get instruction block3
  src/cpu/block3.rs
Labels: fix

#21 [FEAT] Implement tiles map
  src/app.rs
  src/cpu.rs
  src/cpu/utils.rs
  src/gameboy.rs
  src/ppu.rs
  src/ppu/lcd_control.rs
  src/ppu/lcd_status.rs
Labels: enhancement

#23 [FEAT]: add timer in mmu
  src/cpu.rs
  src/cpu/block0.rs
  src/cpu/block2.rs
  src/cpu/block3.rs
  src/cpu/block_prefix.rs
  src/cpu/registers.rs
  src/gameboy.rs
  src/main.rs
  src/mmu.rs
  src/mmu/timers.rs
  src/ppu.rs
Labels: enhancement

#22 [FEAT] Interrupt Handling and HALT
  .gitignore
  src/app.rs
  src/cpu.rs
  src/cpu/block0.rs
  src/cpu/block1.rs
  src/cpu/block2.rs
  src/cpu/block3.rs
  src/mmu.rs
  src/mmu/interrupt.rs
Labels: enhancement

#29 [IMP] 24 - improve naming and refactor functions
  src/cpu.rs
  src/cpu/block0.rs
  src/cpu/block2.rs
  src/cpu/block3.rs
  src/cpu/block_prefix.rs
  src/gameboy.rs
  src/main.rs
  src/mmu.rs
  src/mmu/interrupt.rs
  src/mmu/mbc.rs
  src/ppu.rs
  src/ppu/colors_palette.rs
  src/ppu/lcd_control.rs
  src/ppu/lcd_status.rs
Labels: refacto
