Repository GerardinClement/gbmu, pull requests merged in 2025-06, with the labels that each got.

#2 Implementation of basic memory partitioning
  documentation/Memory Mapping.md
  src/cpu.rs
  src/main.rs
  src/memory/bus.rs
  src/memory/mod.rs
  src/memory/region.rs
Labels: documentation, enhancement

#6 [ADD] Implement use of HL indirect
  src/cpu.rs
  src/cpu/block0.rs
  src/cpu/registers.rs
  src/memory/bus.rs
Labels: enhancement

#10 Read and display tiles from cpu_instrs rom
  .gitignore
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/cpu.rs
  src/cpu/block0.rs
  src/cpu/block2.rs
  src/cpu/block3.rs
  src/cpu/block_prefix.rs
  src/cpu/registers.rs
  src/cpu/utils.rs
  src/gameboy.rs
  src/main.rs
  src/memory/bus.rs
  src/ppu.rs
Labels: enhancement, refacto
